### ISSUE TITLE
Relaton OASIS needs to provide authorship

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-oasis#3]
According to OASIS there are authors/editors listed.

https://www.oasis-open.org/standards/:
<img width="926" alt="Screen Shot 2023-01-12 at 3 20 29 PM" src="https://user-images.githubusercontent.com/11865/212002601-20ebeb5e-83d1-41a1-b488-b8faf75c52ef.png">

In particular the details are given at the standard page:
http://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html

<img width="556" alt="Screen Shot 2023-01-12 at 3 20 54 PM" src="https://user-images.githubusercontent.com/11865/212002696-539c9158-c5e1-4500-b028-ad6612e7a241.png">

NOTE: also the " fetching..." line is missing a closing parenthesis.

```
bundle exec relaton fetch "OASIS mqtt-v5.0"
[relaton-oasis] (OASIS mqtt-v5.0 fetching...
[relaton-oasis] (OASIS mqtt-v5.0) found OASIS mqtt-v5.0
<bibdata type="standard" schema-version="v1.2.1">
  <fetched>2023-01-12</fetched>
  <title type="main" format="text/plain" language="en" script="Latn">MQTT Version 5.0</title>
  <docidentifier type="OASIS" primary="true">OASIS mqtt-v5.0</docidentifier>
  <docnumber>mqtt-v5.0</docnumber>
  <date type="issued">
    <on>2019-03-07</on>
  </date>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn">A Client Server publish/subscribe messaging transport protocol. It is light weight, open, simple, and designed to be easy to implement. These characteristics make it ideal for use in many situations, including constrained environments such as for communication in Machine to Machine (M2M) and Internet of Things (IoT) contexts.</abstract>
  <ext schema-version="v1.0.0">
    <doctype>standard</doctype>
    <editorialgroup>
      <technical-committee>OASIS Message Queuing Telemetry Transport (MQTT) TC</technical-committee>
    </editorialgroup>
    <technology-area>IoT</technology-area>
    <technology-area>Messaging</technology-area>
  </ext>
</bibdata>
```

**Comment by andrew2net** [comment]
> According to OASIS there are authors/editors listed.

@ronaldtse I see only "Editors". Are "Chairs" authors?

**Comment by andrew2net** [comment]
Editors are provided now https://github.com/relaton/relaton-data-oasis/blob/df428d4ab23c5b4777a4f20ac2d8f12c4bce457e/data/MQTT-V5.0.yaml#L28

```sh
$ relaton fetch "OASIS mqtt-v5.0"
[relaton-oasis] (OASIS mqtt-v5.0) fetching...
[relaton-oasis] (OASIS mqtt-v5.0) found OASIS mqtt-v5.0
<bibdata type="standard" schema-version="v1.2.3">
  <fetched>2023-07-25</fetched>
  <title type="main" format="text/plain" language="en" script="Latn">MQTT Version 5.0</title>
  <uri type="src">http://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html</uri>
  <uri type="pdf">http://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.pdf</uri>
  <uri type="doc">http://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.docx</uri>
  <docidentifier type="OASIS" primary="true">OASIS mqtt-v5.0</docidentifier>
  <docnumber>mqtt-v5.0</docnumber>
  <date type="issued">
    <on>2019-03-07</on>
  </date>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <forename language="en" script="Latn">Andrew</forename>
        <surname language="en" script="Latn">Banks</surname>
      </name>
      <affiliation>
        <organization>
          <name>IBM</name>
        </organization>
      </affiliation>
      <email>andrew_banks@uk.ibm.com</email>
    </person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <forename language="en" script="Latn">Ed</forename>
        <surname language="en" script="Latn">Briggs</surname>
      </name>
      <affiliation>
        <organization>
          <name>Microsoft</name>
        </organization>
      </affiliation>
      <email>edbriggs@microsoft.com</email>
    </person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <forename language="en" script="Latn">Ken</forename>
        <surname language="en" script="Latn">Borgendale</surname>
      </name>
      <affiliation>
        <organization>
          <name>IBM</name>
        </organization>
      </affiliation>
      <email>kwb@us.ibm.com</email>
    </person>
  </contributor>
  <contributor>
    <role type="editor"/>
    <person>
      <name>
        <forename language="en" script="Latn">Rahul</forename>
        <surname language="en" script="Latn">Gupta</surname>
      </name>
      <affiliation>
        <organization>
          <name>IBM</name>
        </organization>
      </affiliation>
      <email>rahul.gupta@us.ibm.com</email>
    </person>
  </contributor>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn">A Client Server publish/subscribe messaging transport protocol. It is light weight, open, simple, and designed to be easy to implement. These characteristics make it ideal for use in many situations, including constrained environments such as for communication in Machine to Machine (M2M) and Internet of Things (IoT) contexts.</abstract>
  <ext schema-version="v1.0.0">
    <doctype>standard</doctype>
    <editorialgroup>
      <technical-committee>OASIS Message Queuing Telemetry Transport (MQTT) TC</technical-committee>
    </editorialgroup>
    <technology-area>IoT</technology-area>
    <technology-area>Messaging</technology-area>
  </ext>
</bibdata>
```

**Comment by ronaldtse** [comment]
> > According to OASIS there are authors/editors listed.
> 
> @ronaldtse I see only "Editors". Are "Chairs" authors?

Let’s provide this information too, by using “chair” as a contributor role. 

More importantly, we’re missing the Technical Committee as a contributor.

**Comment by andrew2net** [comment]
@ronaldtse should the Technical Committee be represented as `editorialgroup/technical-committee` and `contributor/organization`?

**Comment by ronaldtse** [comment]
Yes. Thanks!

**Comment by andrew2net** [comment]
> Let’s provide this information too, by using “chair” as a contributor role.

@ronaldtse we don't have "chair" role in the grammar. There are "author", "performer", "publisher", "editor", "adapter", "translator", "distributor", "realizer", "owner", "authorizer", "enabler", and "subject". https://github.com/relaton/relaton-models/blob/d7115ee43416a2d3bd0b050cda687504282f247e/grammars/biblio.rnc#L100

Maybe we should use the "owner"?

**Comment by ronaldtse** [comment]
@andrew2net I believe the "chair" role might work best as "authorizer". Thoughts @opoudjis ?

**Comment by opoudjis** [comment]
No, I don't agree, the authoriser is someone who lends their institutional prestige to the publication, the chair is whoever got voted in this year as the lead of the technical committee. The chair doesn't play the role that NIST or OASIS does. The chair is acting as a lead editor, if we allow the technical committee to have an editorial role (even if they're delegating the work to the actual editors). So `/contributor/role[type = 'editor'][description = 'chair']`.

**Comment by ronaldtse** [comment]
> The chair is acting as a lead editor

I'm not sure if this is a correct assumption. The significance of the "chair" of the TC is that the TC is one of the authorizers of the document.

**Comment by opoudjis** [comment]
In that OASIS authorises the document as a body, but delegates the decision and process around authorisation to the TC, and the Chair manages that process.

I'm still uncomfortable with this, because the Chair has much more of a hands-on, managerial responsibility; but if the Chair says "imprimatur" ("this is good to go") on behalf of OASIS, then yes, the role is authorizer.

**Comment by andrew2net** [comment]
@ronaldtse is this ok? https://github.com/relaton/relaton-data-oasis/blob/main/data/MQTT-V5.0.yaml

**Comment by ronaldtse** [comment]
There are several things to address.

## OASIS is the authorizer and publisher

Add this:

```
- organization:
    name:
    - content: OASIS
    contact:
    - uri: https://www.oasis-open.org
  role:
  - type: authorizer
  - type: publisher
```

## OASIS TC is the editorial committee

@opoudjis should the TC be an authorizer or a publisher or what else?

```
- organization:
    name:
    - content: OASIS Message Queuing Telemetry Transport (MQTT) TC
    contact:
    - uri: https://www.oasis-open.org/committees/mqtt/
  role:
  - type: authorizer
```

## Chair still missing

```
- person:
    name:
      given:
        forename:
        - content: Richard
          language:
          - en
          script:
          - Latn
      surname:
        content: Coppen
        language:
        - en
        script:
        - Latn
    affiliation:
    - organization:
        name:
        - content: IBM
        contact:
        - uri: http://www.ibm.com
    contact:
    - email: coppen@uk.ibm.com
  role:
  - type: editor
    description: Chair
```

**Comment by andrew2net** [comment]
> Chair still missing

@ronaldtse do you mean `authorizer`? We don't have `chair` in our data model.
Look updated document https://github.com/relaton/relaton-data-oasis/blob/main/data/MQTT-V5.0.yaml

**Comment by opoudjis** [comment]
> OASIS TC is the editorial committee

> @opoudjis should the TC be an authorizer or a publisher or what else?

And that's the problem with introducing these fine shades of distinction, people now have to make them. They're either an editor, or an authorizer, they're not making the document available themselves. I would prefer to call them editors, but you can argue for both roles. (They both prepare the document for publication, and approve it.)

> Chair still missing

No it isn't:

````
 role:
  - type: editor
    description: Chair
````

That is exactly where Chair belongs, role/type is a tightly constrained vocabulary, and chair has nothing to do with it.

**Comment by andrew2net** [comment]
> ## OASIS TC is the editorial committee
> @opoudjis should the TC be an authorizer or a publisher or what else?
> 
> ```
> - organization:
>     name:
>     - content: OASIS Message Queuing Telemetry Transport (MQTT) TC
>     contact:
>     - uri: https://www.oasis-open.org/committees/mqtt/
>   role:
>   - type: authorizer
> ```

@opoudjis what about this?

**Comment by opoudjis** [comment]
I think @ronaldtse is failing to think this through.

If both OASIS and the OASIS TC are now authorizers, then how is a consumer meant to tell them apart? You cannot just put in three contributors with the same role and no further disambiguation, when they do not contribute in the same way, and they are not the same kind of thing: OASIS is a superset of the OASIS TC. This is going to be unreasonably confusing for consumers, and Andrej, you are not to allow this confusion to continue. The point of adding "authorizer" was to make things more clear, not less.

If you *ever* call a technical or other committee an authorizer, you MUST add the description "Committee" to it. That way, we can tell which is the committee and which is the overall organisation or sponsor. If you add OASIS as a separate authorizer, give it the description "Standards Development Organization". And please generalise that practice to all of Relaton.

**Comment by andrew2net** [comment]
@ronaldtse fixed https://github.com/relaton/relaton-data-oasis/blob/main/data/MQTT-V5.0.yaml
