### ISSUE TITLE
Better documentation on where to find the ID for citing

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-oasis#4]
The syntax "OASIS mqtt-v5.0" is very hard to find out and is not documented in the README.

The way to find the ID is:
1. Go to https://www.oasis-open.org/standards/
2. Locate the standard
3. Locate the "cite as" line. e.g.
```
Cite as: 
[mqtt-v5.0]
MQTT Version 5.0. Edited by Andrew Banks, Ed Briggs, Ken Borgendale, and Rahul Gupta. 07 March 2019.
OASIS Standard. http://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html.
Latest version: http://docs.oasis-open.org/mqtt/mqtt/v5.0/mqtt-v5.0.html.
```
4. Then the ID is `mqtt-v5.0`.

Perhaps we need some way to visualize all this information. The data is all available at: https://github.com/relaton/relaton-data-oasis

(Relaton API is also not working as I type.)

**Comment by andrew2net** [comment]
@ronaldtse unfortunately not every document has a "Cite as" line. In such cases, IDs are created by parsing titles. It's difficult for users to figure out a reference from a title. I think we should make an index.

**Comment by ronaldtse** [comment]
Yes I agree with making an index using GitHub Pages (see https://github.com/actions/deploy-pages)

**Comment by andrew2net** [comment]
@ronaldtse made the basic designed index page generator https://relaton.github.io/relaton-data-oasis/

**Comment by ronaldtse** [comment]
@andrew2net this is good. Can we apply this across all the relaton-data-* repositories? Ultimately we want to offer all this information through relaton.org.
