### ISSUE TITLE
Unsupported technology areas

### ISSUE THREAD

**Issue by andrew2net** [relaton/relaton-oasis#6]
The Relaton OASIS data model has a list of technology areas https://github.com/relaton/relaton-model-oasis/blob/98d734f91e066f9c699f8d1f5b0832fceb0328fd/grammars/relaton-oasis.rnc#L19-L35

There are technology areas that aren't included in the list:
- Software-development
- Virtualization

We need to add these terms to the grammar.

**Comment by opoudjis** [comment]
"Software-Development", for consistency with the rest of the list.
